# Generated by Django 2.1.7 on 2019-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('responsavel', models.CharField(max_length=20)),
                ('prazo', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feita', models.BooleanField(default=False)),
            ],
        ),
    ]
